  
kind: pipeline
type: docker
name: default

steps:
  - name: build
    image: plugins/docker
    settings:
      username: kitkit
      password:
        from_secret: DOCKER_HUB_PASSWORD
      context: build
      dockerfile: build/Dockerfile
      repo: kitkit/rabbitmq
      tags: 3.8.9-management-with-delayed

# trigger:
#   ref:
#     - refs/tags/**